const CUSTOMER_LIST_TYPES = {
  CUSTOMER_LIST_LOADING: "CUSTOMER_LIST_LOADING",
  CUSTOMER_LIST_FAIL: "CUSTOMER_LIST_FAIL",
  CUSTOMER_LIST_SUCCESS: "CUSTOMER_LIST_SUCCESS",
};

export default CUSTOMER_LIST_TYPES;
